package com.pojos.model;
// Generated Jun 3, 2016 4:36:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name="contacts"
    ,catalog="demo"
)
public class Contacts  implements java.io.Serializable {


     private Integer id;
     private Date birthdate;
     private String cellNo;
     private String country;
     private Date created;
     private String emailId;
     private String firstname;
     private String lastname;
     private String sex;
     private String website;

    public Contacts() {
    }

	
    public Contacts(Date created) {
        this.created = created;
    }
    public Contacts(Date birthdate, String cellNo, String country, Date created, String emailId, String firstname, String lastname, String sex, String website) {
       this.birthdate = birthdate;
       this.cellNo = cellNo;
       this.country = country;
       this.created = created;
       this.emailId = emailId;
       this.firstname = firstname;
       this.lastname = lastname;
       this.sex = sex;
       this.website = website;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)

     //@GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", length=10)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="cell_no", length=15)
    public String getCellNo() {
        return this.cellNo;
    }
    
    public void setCellNo(String cellNo) {
        this.cellNo = cellNo;
    }

    
    @Column(name="country", length=30)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="email_id", length=30)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="firstname", length=30)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", length=30)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="website", length=150)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    
        //This method writes the values of contact object with System.out.println(contact.toString()) code
    @Override
    public String toString() {
    return "Contact"
    + "\n\t Id: " + this.id
    + "\n\t FirstName: " + this.firstname
    + "\n\t LastName: " + this.lastname
    + "\n\t Sex: " + this.sex 
    + "\n\t CellNo: " + this.cellNo
    + "\n\t Country: " + this.country 
    + "\n\t WebSite: " + this.website        
    + "\n\t EmailId: " + this.emailId
    + "\n\t BirthDate: " + this.birthdate
    + "\n\t Date Created: " + this.created;
    }





}


